#WRITE A PROGRAM TO ENTER PRINCIPAL AMOUNT, TIME AND INTEREST RATE. CREATE SIMPLE_INTEREST(PRINCIPAL,TIME,RATE) FUNCTION TO CALCULATE SIMPLE INTEREST.
PA1=int(input("ENTER THE PRINCIPAL AMOUNT"))
T1=int(input("ENTER THE TIME"))
IR1=int(input("ENTER THE INTEREST RATE"))
def simple_interest(PA,T,IR):
    SI=PA*T*(IR/100)
    print("SIMPLE INTEREST=",SI)
SI1=simple_interest(PA1,T1,IR1)
