#WRITE A PROGRAM TO ENTER PRINCIPAL AMOUNT, TIME AND INTEREST RATE. CREATE COMPOUND_INTEREST(PRINCIPAL,TIME,RATE) FUNCTION TO CALCULATE COMPOUND INTEREST.
PA1=int(input("ENTER THE PRINCIPAL AMOUNT"))
T1=int(input("ENTER THE TIME"))
IR1=int(input("ENTER THE INTEREST RATE"))
def compound_interest(PA,T,IR):
    i=1
    CI=0
    while(i<=T):
        C=PA*IR/100
        PA=PA+C
        CI=CI+C
        i =i+1
    print("COMPOUND INTEREST IS",CI)
C1=compound_interest(PA1,T1,IR1)
